### ISSUE TITLE
yo: add new notifications system - Yotifications!

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2102]
- [x] tarantool audit #2309 
- [x] feature flags #2179
- [x] wrap old notification system in feature flags #2103
- [x] wrap new notification system in feature flags #2613
- [ ] refactor previously created reducers to fit new ducks standards #2201
- [ ] todo: see where yo is at & add new sub-issues here (#2928 spike)

**Comment by relativityboy** [comment]
Just when you thought Yotifications wasn't coming...  ![Yotifications rises from the deep](http://www.army-technology.com/wp-content/uploads/sites/3/2017/09/Norways-joint-sub-plan-6.jpg)


Over time, we'll be supporting a few different types, which can be enabled or disabled at will.
![Image of the Yotifications delivery system](https://upload.wikimedia.org/wikipedia/commons/5/51/USS_Santa_Fe_%28SSN-763%29_VLS_doors_open.jpg)

**Comment by bnchdrff** [comment]
the latest notification work is in https://github.com/steemit/condenser/tree/notification-ui-rebased-squashed

**Comment by roadscape** [comment]
Very stale, closing for now
