### ISSUE TITLE
Add feature flags (ability to turn aspects of condenser on and off)

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#2179]
# Subissues

* [x] create feature flag HoC `Flag`: model its API after unbounce/flag
* [x] add feature flag `Map` to our state tree, probably next to other user settings in AppReducer; model its shape after unbounce/flag
* [x] create a `withFlagState` container for `Flag` which subscribes to the flag part of the state tree - #2273 
* [x] update steem-js to 0.7.1 so we can fetch flags (done in PR)
* [ ] add steemitapi.get_feature_flags to jussi
* [ ] figure out what is blocking the get_feature_flags endpoint & solve any issues
* [x] add saga to fetch flags - saga should deal gracefully with the flag endpoint not working at all #2375 (done in PR)
* [x] figure out issue with initial state not having defaults #2377 (done in PR)
* [x] add documentation w/ example #2376

It would be really nice to have "feature flags" that would either be part of condenser's configuration, or found via an API call. The flags would allow us to turn features (ex for non-extant features: notifications, live comment count/second tickers) on or off for a given instance of condenser.

The API call component of this would be handled by [conveyor](https://github.com/steemit/conveyor) (formerly steemitapi). It was [issue 5](https://github.com/steemit/conveyor/issues/5) and [PR 4](https://github.com/steemit/conveyor/pull/4) in that codebase.

JSON-RPC Request Example:
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "conveyor.get_feature_flags",
    "params": {"username": "jnordberg"}
}
```
The return value is an object with key value pairs `{flag_name: boolean}`. Absence of a flag is equivalent to false.

As a part of condenser's local configuration, they would mimic the structure of the RPC call's response, and deferring to the RPC result unless a css like _!important_ was added to a flag (mechanism tbd). There will also be a local setting for turning off the API call entirely; relying only on the local config.

**Logging & Other**
This Issue only covers the consumption of the feature flags themselves, and enabling/disabling the associated features. It is not intended to include special capabilities _implied_ by feature flags.

**Comment by goldibex** [comment]
Why is there an RPC API for this? Why not just build-time flags?
```yarn start --experimental-thing1 --experimental-thing2```

**Comment by sneak** [comment]
To turn it on for eg 1% of users at runtime and without a deploy, obvs. :)

**Comment by relativityboy** [comment]
@goldibex - we had a discussion about it in late September / early October to get clarity before @jnordberg implemented it. 

@goldibex @sneak Please add a 👍  on the root comment if this looks good enough for us to proceed. A 🔢 if you think it still needs work.
 If you want changes, communicate clearly and I'll update the root comment when we have consensus @ which point you can 👍

**Comment by goldibex** [comment]
Okay, so a discussion did happen, it just happened before I existed. Good enough for me.

**Comment by goldibex** [comment]
@relativityboy please coordinate with @jnordberg on integration and link all associated PRs to this issue

**Comment by sneak** [comment]
The way it works is thus:

there’s a call, called something like get_feature_flag(flagname) or somesuch, that is made to conveyor by the client, signed with a given userid.

If the user has a defined boolean set for that flag on their account in conveyor, we serve that for the flag. This allows us to enable/disable flags on a per-user basis by setting that user’s specific feature flag to true/false.

the other set of feature flags, the undefined ones, when read in this manner are probabilisticly (and deterministically) derived from a hash of the username and a percentage enable probability for that flag, and then returned.  basically, you can do something like specifying n/256 probability the flag will be enabled, and seeing if the last byte of the hash of the username and flagname is below n, and, if so, enable it.  it should also probably be stored, so users don’t lose features if we change the rollout percentage for something from 10 to 5 later - users that had it should keep it, so the deterministic generation is probably overkill - it should be saved to the db on first read.

this means that we will also need calls in conveyor to define a new feature flag, and to change its probability percentage after it is created, and finally a call to update all users to have it turned on (e.g. if it were deployed with 10% enabled, and 90% of users got flagged `false`).

i realize this doesn’t really allow for a staged rollout, like 1%, then 10%, then 20%, then 50%, then 100%, without updating a lot of rows in the db.  i’m sort of sleep deprived today and i may not be fully remembering the conversation with @jnordberg - i feel like we had solved these problems then.

**Comment by sneak** [comment]
looks like we didn’t, having read the code, unless i’m misunderstanding it.  discussion around use cases is here: https://github.com/steemit/conveyor/issues/17

**Comment by sneak** [comment]
design-wise, condensor should not know anything about how feature flags are set, stored, probabilisticaly enabled, or otherwise. that should remain entirely within `conveyor`, and condenser should just call to it to receive true/false values for a given flag+user tuple.

**Comment by sneak** [comment]
condenser may safely assume a false value for a feature flag that is undefined in the conveyor response. conveyor is responsible for all probabilistic rollouts, not condenser.

**Comment by bnchdrff** [comment]
on the condenser side of things, i think we should keep track of the user's feature flags in the user portion of our redux state. we should fetch once when the user is logged in, and potentially even poll (probably infrequently) for changes.

how can we include a user's feature flags in logging calls to overseer? is that up to us on the condenser end or can that mapping happen on the overseer side?

**Comment by relativityboy** [comment]
@bnchdrff 💯 
If our logging includes a feature id, We should be able to assume a user has that flag enabled. Posting the feature flag state of the user _would_ give us more clarity.

@sneak those are some pretty good spec-comments. I hope @goldibex can integrate them into our backlog as an [epic](https://www.agilealliance.org/glossary/epic)

**Comment by relativityboy** [comment]
Data analysis is critical, and logging is worthy of its own issue. #2209 has been created to focus our efforts.

**Comment by bnchdrff** [comment]
I think we should use [unbounce's flag component](https://github.com/unbounce/flag) -- it's small, has good test coverage, and does what we want it to do & nothing more. We should use their `createFlagsReducer` to store flag state. We can add to our `UserSaga` to load a user's flag state from `conveyor` on login & dispatch a `setFlagsAction` based on the response. We can set default flag values when we create the reducer initially -- those will be used when the SSR version of the page is built.

How does this sound?

**Comment by bnchdrff** [comment]
Nevermind about `unbounce/flag` -- it depends on react v16. we'll write our own, but follow its example. it's not that bad.

**Comment by bnchdrff** [comment]
how does this sound? the gist of it is we'd write a wrapper component that takes a feature flag & two components as props; one component would render if the flag is enabled, and the other would render if the flag is disabled.

**Comment by relativityboy** [comment]
If the effort to get us on React v16 is lower, or the same as, implementing our own flag system then it's time for us to move to 16.

**Comment by bnchdrff** [comment]
todo:

* [ ] create feature flag HoC `Flag`: model its API after unbounce/flag
* [ ] add feature flag `Map` to our state tree, probably next to other user settings in AppReducer; model its shape after unbounce/flag
* [ ] create a `withFlagState` container for `Flag` which subscribes to the flag part of the state tree

**Comment by bnchdrff** [comment]
@jnordberg we'll need to update `@steemit/steem-js` to 0.7.0 to do signed calls to get the flags, correct?

**Comment by relativityboy** [comment]
@bnchdrff @jnordberg - there's a possible issue with 0.6.9+. The ACCEPT headers added to RPC calls were triggering browser OPTIONS calls, and could cause endpoints to return 405s if they don't support it. 
We need to revert that addition to steem-js, or make sure all our endpoints are gtg.

**Comment by bnchdrff** [comment]
let's move that discussion to steemit/steem-js @relativityboy

**Comment by jnordberg** [comment]
@bnchdrff signedCall arrived in steem-js 0.6.10

**Comment by bnchdrff** [comment]
we're on 0.6.8 now; should we move to 0.6.10 or straight to 0.7.0 @jnordberg ?
